#!/bin/sh
#
# riley-turnin - a simple homework turn in script.
#
# USAGE:  riley-turnin dirname
#

SCRIPT_NAME=$(basename "${BASH_SOURCE[0]}")
#CLASS_NAME=$(cut -d'-' -f2 <<< $SCRIPT_NAME)
DIR=/nethome/$SCRIPT_NAME


# Check that a directory name was given as an argument
if [ $# -eq 0 ]; then
  echo "ERROR: No directory to turn in provided."
  echo "USAGE: $SCRIPT_NAME dirname"
  exit 1
fi

if [ ! -d $1 ]; then
    echo "ERROR: $1 does not exist or is not a directory. Please check and try again."
    exit 1
fi

if [ ! -r $1 ]; then
    echo "ERROR: Directory $1 is not readable."
    exit 1
fi

# Make a tarball and copy it to turn-in directory
TURNIN_DIR=`echo $1 | sed -e 's/\/$//'`
tar -czf - $TURNIN_DIR | dd of=$DIR/$USER-$TURNIN_DIR.tar.gz
if [ $? -ne 0 ]; then
   echo "ERROR: Turnin Failed ($?)!  Sorry.  Please contact your professor!"
   exit 1
else
   echo
   echo "Good News.  Exit code=0: Turnin Successful!"
fi
